+++
"date" = "2023-03-23"
"description" = "Description of the products page"
"keywords" = "products, page, description"
"layout" = "page"
"permalink" = "/products/"
"title" = "Products"
"image" = "https://kura.pro/shokunin/images/logos/shokunin.svg"
+++

This is the products page.
